[graph]
all-features = true

[sources]
unknown-registry = "deny"

[bans]
deny = [
    { name = "openssl-sys", reason = "increases complexity for foreign binding compilation and bundle size" },
    { name = "openssl", reason = "increases complexity for foreign binding compilation and bundle size" },
]

[licenses]
version = 2
confidence-threshold = 1.0
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "Unicode-3.0",
    "Unlicense",
]

[[licenses.clarify]]
crate = "webpki" # `webpki` is ISC but missing the field
expression = "ISC"
license-files = [{ path = "LICENSE", hash = 0x001c7e6c }]

[advisories]
ignore = [
    "RUSTSEC-2021-0127", # Unmaintained `serde_cbor` (requires upstream update, see https://github.com/aws/aws-nitro-enclaves-nsm-api/pull/56)
]
