use std::{
	collections::HashMap,
	time::{SystemTime, UNIX_EPOCH},
};

use base64::{Engine, engine::general_purpose::STANDARD};
use coset::{CborSerializable, Header, ProtectedHeader};
use serde_bytes::ByteBuf;

use super::*;
use crate::nsm::Digest;

// Helper function that provides a full attestation document with real PCR values generated by an enclave at the time.
// Since the attestation document is only valid for a few hours, we need to create a custom verifier with an extended max age to handle expired attestations for testing.
// Additionally we bypass the certificate expiration check to allow testing with expired documents.
fn get_real_attestation_document() -> (EnclaveAttestationVerifier, String) {
	let attestation_doc_base64 = "hEShATgioFkRI79pbW9kdWxlX2lkeCdpLTAxYjMyNGYwYjhiNmMyNWVhLWVuYzAxOTk3NjY4YmRhMzhiMmFmZGlnZXN0ZlNIQTM4NGl0aW1lc3RhbXAbAAABmXZu/3tkcGNyc7AAWDAQizJGb13AqZceC8jj5AdOeCG7LcrThBveyaCLMPFzOG8DlKAUht8YHzFrOUQ9qzQBWDBLTVs2YbPvwSkgkAyA4Sbkzng8Ui3mwCoqW/evOiuTJ7hndvGI5L4cHEBKEp29pJMCWDAIxrLLotDAq2PzUzy0TgkvshF3UyPNYs1XH4ceEnrhhE8OlIpUuljs0p++A6ZNXtwDWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEWDDnitfljKBgmk5ecClc2b3mOSYfYR2rrl/OdraESOcitzapDbsXmSZCYqqZKg806x0FWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWDCzglFmIDM0C1QMLX5fSefsbRCvy18XxyEy4gp/ClRXbcTSxs4GLtLtK2rgGBXWnI0JWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABrY2VydGlmaWNhdGVZAn8wggJ7MIICAaADAgECAhABmXZovaOLKgAAAABo0osBMAoGCCqGSM49BAMDMIGOMQswCQYDVQQGEwJVUzETMBEGA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEPMA0GA1UECgwGQW1hem9uMQwwCgYDVQQLDANBV1MxOTA3BgNVBAMMMGktMDFiMzI0ZjBiOGI2YzI1ZWEudXMtZWFzdC0xLmF3cy5uaXRyby1lbmNsYXZlczAeFw0yNTA5MjMxMTU2NDZaFw0yNTA5MjMxNDU2NDlaMIGTMQswCQYDVQQGEwJVUzETMBEGA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEPMA0GA1UECgwGQW1hem9uMQwwCgYDVQQLDANBV1MxPjA8BgNVBAMMNWktMDFiMzI0ZjBiOGI2YzI1ZWEtZW5jMDE5OTc2NjhiZGEzOGIyYS51cy1lYXN0LTEuYXdzMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEstDYvyJXUx1jFw0w6fNTL/B6NRJv4ZFMVoA5ofIs9d8bJYL1gGRnGpO3solnhUUmE4v64SQohcG4YBKapifEm9MRRgdUjrz/L92nDbClT3VUSSDrT7zxLCVHtZOS63DJox0wGzAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwIGwDAKBggqhkjOPQQDAwNoADBlAjAqbEqI+T3QMFTPHGurfIIY8gU+t4iDlAYeCTiSGKzbaD2aeLfBBH+kDJi9wlz7i2ECMQDEJnQKdm+ncv95Qq85BPFarWJcFVrtZLIkBUCIZFgUWnCyIkdkXl1r9+Jm1xRPlFdoY2FidW5kbGWEWQIVMIICETCCAZagAwIBAgIRAPkxdWgbkK/hHUbMtOTn+FYwCgYIKoZIzj0EAwMwSTELMAkGA1UEBhMCVVMxDzANBgNVBAoMBkFtYXpvbjEMMAoGA1UECwwDQVdTMRswGQYDVQQDDBJhd3Mubml0cm8tZW5jbGF2ZXMwHhcNMTkxMDI4MTMyODA1WhcNNDkxMDI4MTQyODA1WjBJMQswCQYDVQQGEwJVUzEPMA0GA1UECgwGQW1hem9uMQwwCgYDVQQLDANBV1MxGzAZBgNVBAMMEmF3cy5uaXRyby1lbmNsYXZlczB2MBAGByqGSM49AgEGBSuBBAAiA2IABPwCVOumCMHzaHDimtqQvkY4MpJzbolL//Zy2YlES1BR5TSksfbb48C8WBoyt7F2Bw7eEtaaP+ohG2bnUs990d0JX28TcPQXCEPZ3BABIeTPYwEoCWZEh8l5YoQwTcU/9KNCMEAwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUkCW1DdkFR+eWw5b6cp3PmanfS5YwDgYDVR0PAQH/BAQDAgGGMAoGCCqGSM49BAMDA2kAMGYCMQCjfy+Rocm9Xue4YnwWmNJVA44fA0P5W2OpYow9OYCVRaEevL8uO1XYru5xtMPWrfMCMQCi85sWBbJwKKXdS6BptQFuZbT73o/gBh1qUxl/nNr12UO8Yfwr6wPLb+6NIwLz3/ZZAsIwggK+MIICRaADAgECAhEAnz7cA+jkWKueDDufFa7mETAKBggqhkjOPQQDAzBJMQswCQYDVQQGEwJVUzEPMA0GA1UECgwGQW1hem9uMQwwCgYDVQQLDANBV1MxGzAZBgNVBAMMEmF3cy5uaXRyby1lbmNsYXZlczAeFw0yNTA5MTgwMDMyNTVaFw0yNTEwMDgwMTMyNTVaMGQxCzAJBgNVBAYTAlVTMQ8wDQYDVQQKDAZBbWF6b24xDDAKBgNVBAsMA0FXUzE2MDQGA1UEAwwtNGIxMTRlYjgxNWJmYWFiNC51cy1lYXN0LTEuYXdzLm5pdHJvLWVuY2xhdmVzMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEdXxXovmqlOGQVbPzU2hqeEohRzP6Z9ToQXPPGyV/DB4uHNwRqNser2C8VnEbWxuDztbtrKFm7h5XdIndkC6kMv8zBVx1fHuS0GiSK12ejXHbDCmcNkP3KvLPcqC/Q79uo4HVMIHSMBIGA1UdEwEB/wQIMAYBAf8CAQIwHwYDVR0jBBgwFoAUkCW1DdkFR+eWw5b6cp3PmanfS5YwHQYDVR0OBBYEFLquiqt5Qe7MA1g9fVQH8hKcCvsDMA4GA1UdDwEB/wQEAwIBhjBsBgNVHR8EZTBjMGGgX6BdhltodHRwOi8vYXdzLW5pdHJvLWVuY2xhdmVzLWNybC5zMy5hbWF6b25hd3MuY29tL2NybC9hYjQ5NjBjYy03ZDYzLTQyYmQtOWU5Zi01OTMzOGNiNjdmODQuY3JsMAoGCCqGSM49BAMDA2cAMGQCMAjWfjbqHL2wIwD7Eep3hrg2bKUm5Gf6EBVG/ZZztuKZs4nelgopHzTJsiQgntB4rwIwN3efCtE2UnPKUI6C3sAY7rv3GmiWdNKptEGeMi0lzErihMRE7IegjhSc9dHqP83RWQMaMIIDFjCCApugAwIBAgIRANq7IEjBcBA1E33Kd04JWpkwCgYIKoZIzj0EAwMwZDELMAkGA1UEBhMCVVMxDzANBgNVBAoMBkFtYXpvbjEMMAoGA1UECwwDQVdTMTYwNAYDVQQDDC00YjExNGViODE1YmZhYWI0LnVzLWVhc3QtMS5hd3Mubml0cm8tZW5jbGF2ZXMwHhcNMjUwOTIyMTgxOTUzWhcNMjUwOTI4MTUxOTUzWjCBiTE8MDoGA1UEAwwzNTU5MmYwZTNiODQ1NzVkMy56b25hbC51cy1lYXN0LTEuYXdzLm5pdHJvLWVuY2xhdmVzMQwwCgYDVQQLDANBV1MxDzANBgNVBAoMBkFtYXpvbjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAldBMRAwDgYDVQQHDAdTZWF0dGxlMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEnwi69NZ3bI6vzW3wAVbThsOjJ1zeMygejq4ubzd9PGU5oFQ9lrxaTG2Z7VifRFelLD7CLY7YPzOc5mGKYcTVvyYaB7EjX6t3zl6pIzBX4QYtdak2EnwBwp6GsUoJI+9zo4HqMIHnMBIGA1UdEwEB/wQIMAYBAf8CAQEwHwYDVR0jBBgwFoAUuq6Kq3lB7swDWD19VAfyEpwK+wMwHQYDVR0OBBYEFMZwznd97tj3asGwQdVlHs9QucKZMA4GA1UdDwEB/wQEAwIBhjCBgAYDVR0fBHkwdzB1oHOgcYZvaHR0cDovL2NybC11cy1lYXN0LTEtYXdzLW5pdHJvLWVuY2xhdmVzLnMzLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tL2NybC9iMzZhNjg5Yi0yODk4LTQ1NGUtYjIxZS1kZmE2NDBlNDk5Y2QuY3JsMAoGCCqGSM49BAMDA2kAMGYCMQCot2p082m40njsFz6K99bV1tghUya+WWoF1/dnsIXvX8zKsFcYRUadlphzYGDbv2cCMQDNp0whSKs18dOZmADPveiy+87lEg9MWhR/ZuGXK/Ltu71lgW6t4Q+Q+o4O4nTAvHRZAsMwggK/MIICRaADAgECAhUAi8L8dkb0zqPy5OpeuM/ni9fK4icwCgYIKoZIzj0EAwMwgYkxPDA6BgNVBAMMMzU1OTJmMGUzYjg0NTc1ZDMuem9uYWwudXMtZWFzdC0xLmF3cy5uaXRyby1lbmNsYXZlczEMMAoGA1UECwwDQVdTMQ8wDQYDVQQKDAZBbWF6b24xCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJXQTEQMA4GA1UEBwwHU2VhdHRsZTAeFw0yNTA5MjMwNTQzMDhaFw0yNTA5MjQwNTQzMDhaMIGOMQswCQYDVQQGEwJVUzETMBEGA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEPMA0GA1UECgwGQW1hem9uMQwwCgYDVQQLDANBV1MxOTA3BgNVBAMMMGktMDFiMzI0ZjBiOGI2YzI1ZWEudXMtZWFzdC0xLmF3cy5uaXRyby1lbmNsYXZlczB2MBAGByqGSM49AgEGBSuBBAAiA2IABNkZcqC72Yizp5Fon8A3k5lEwZTFIdxkdf1JAjQnb/6MWXaga2z1ijL5rjMMp4iTf42Oad9orhxGQSSgUwVsdSt864uyX/rxJfdY1yfYtRYEr6VoEmn2wYYYPSk4KXwRoqNmMGQwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAgQwHQYDVR0OBBYEFGUYBnz1xoBcsPIWl5MQDMuP0r3tMB8GA1UdIwQYMBaAFMZwznd97tj3asGwQdVlHs9QucKZMAoGCCqGSM49BAMDA2gAMGUCMQDDZY2l9NDyjOWRMrC4PQKSrmvoDwiUc/CciZjmu4xwoh4ERQfCJoKWvIE8feFPhLoCMGoIObYePGptEWRQOlB3NK47/30pnxFC9JsZXH24b5CwVd2Y9g9cRSw8xCWySyv5FGpwdWJsaWNfa2V5WCBDuYZGG723Ut04no82MS5evDN3+R5pTYEl0bwAebLhIml1c2VyX2RhdGH2ZW5vbmNl9v9YYIUaRE7Zp3BwAfCTvn8qXy0w26nhRNuA62Z7RyeHmk5mvbEH5y6pddibFhHtufy3gmXKdG49aKHUGJLcHESCRNmHBAJNIdmemKLj544GsgL825nxMkSkliJmAPne41e1wA==";
	// Create a custom verifier with extended max age to handle expired attestations for testing
	let pcr_configs = vec![]; // We'll add them below
	let root_cert = super::constants::AWS_NITRO_ROOT_CERT.to_vec();
	let ten_years_in_milliseconds = 10 * 365 * 24 * 60 * 60 * 1000; // 10 years in milliseconds (for testing)

	let mut verifier = EnclaveAttestationVerifier::new_with_config_and_time_skip(
		pcr_configs,
		root_cert,
		ten_years_in_milliseconds,
		true, // Skip certificate time checks for testing
	);

	// These are real PCR values generated by an enclave in time
	verifier.add_allowed_pcr_config(vec![
		PcrMeasurement::new(
			0,
			hex_literal::hex!(
				"108b32466f5dc0a9971e0bc8e3e4074e7821bb2dcad3841bdec9a08b30f173386f0394a01486df181f316b39443dab34"
			),
		),
		PcrMeasurement::new(
			1,
			hex_literal::hex!(
				"4b4d5b3661b3efc12920900c80e126e4ce783c522de6c02a2a5bf7af3a2b9327b86776f188e4be1c1c404a129dbda493"
			),
		),
		PcrMeasurement::new(
			2,
			hex_literal::hex!(
				"08c6b2cba2d0c0ab63f3533cb44e092fb211775323cd62cd571f871e127ae1844f0e948a54ba58ecd29fbe03a64d5edc"
			),
		),
		PcrMeasurement::new(
			8,
			hex_literal::hex!(
				"b38251662033340b540c2d7e5f49e7ec6d10afcb5f17c72132e20a7f0a54576dc4d2c6ce062ed2ed2b6ae01815d69c8d"
			),
		),
	]);

	(verifier, attestation_doc_base64.to_string())
}

// This tests verifies a real attestation document with real PCR values.
#[test]
fn test_real_attestation_document() {
	let (verifier, attestation_doc_base64) = get_real_attestation_document();

	let attestation_doc_bytes = STANDARD
		.decode(attestation_doc_base64)
		.expect("Failed to decode base64");

	verifier
		.verify_document(&attestation_doc_bytes)
		.expect("attestation verification failed");
}

// Failure cases
/// Configuration for generating basic fake attestation documents
#[derive(Debug, Clone)]
struct SimpleFakeAttestationConfig {
	/// Module ID for the attestation
	module_id: String,
	/// PCR values to include in the attestation
	pcr_values: HashMap<usize, Vec<u8>>,
	/// Custom timestamp (None = current time)
	timestamp: Option<u64>,
	/// DER bytes used for both the leaf certificate and the CA bundle
	certificate: Vec<u8>,
}

impl Default for SimpleFakeAttestationConfig {
	fn default() -> Self {
		Self {
			module_id: "i-test123456789abcdef0-enc0123456789abcdef0".to_string(),
			pcr_values: HashMap::new(),
			timestamp: None,
			certificate: vec![0x30, 0x82, 0x01, 0xFF],
		}
	}
}

/// Generate a minimal fake attestation document CBOR for testing
/// This creates invalid attestation documents that can be used to test specific error conditions
fn generate_simple_fake_attestation_self_signed(
	config: &SimpleFakeAttestationConfig,
) -> EnclaveAttestationResult<Vec<u8>> {
	let timestamp = config.timestamp.unwrap_or_else(|| {
		u64::try_from(
			SystemTime::now()
				.duration_since(UNIX_EPOCH)
				.unwrap()
				.as_millis(),
		)
		.unwrap_or(u64::MAX)
	});

	let doc = AttestationDoc {
		module_id: config.module_id.clone(),
		digest: Digest::SHA384,
		timestamp,
		pcrs: config
			.pcr_values
			.iter()
			.map(|(index, value)| (*index, ByteBuf::from(value.clone())))
			.collect(),
		certificate: ByteBuf::from(config.certificate.clone()),
		cabundle: vec![ByteBuf::from(config.certificate.clone())],
		public_key: Some(ByteBuf::from(vec![0x04; 65])),
		user_data: None,
		nonce: None,
	};

	let mut payload = Vec::new();
	ciborium::into_writer(&doc, &mut payload).map_err(|e| {
		EnclaveAttestationError::AttestationDocumentParseError(format!(
			"Failed to serialize fake attestation document: {e}"
		))
	})?;

	// Built through coset so the envelope is structurally valid COSE_Sign1. A fixture that fails
	// at the parser cannot exercise the chain, signature or PCR stages it is named for.
	CoseSign1 {
		protected: ProtectedHeader::default(),
		unprotected: Header::default(),
		payload: Some(payload),
		signature: vec![0x00; 96],
	}
	.to_vec()
	.map_err(|e| {
		EnclaveAttestationError::AttestationDocumentParseError(format!(
			"Failed to encode fake COSE Sign1: {e}"
		))
	})
}

/// Decode the real attestation document used by the positive tests.
fn real_attestation_bytes() -> Vec<u8> {
	let (_, attestation_doc_base64) = get_real_attestation_document();
	STANDARD
		.decode(attestation_doc_base64)
		.expect("Failed to decode base64")
}

/// Flip one bit of the real document's signature, leaving every other byte untouched.
///
/// The signature is the trailing 96-byte bstr of the `COSE_Sign1` array, so mutating the last byte
/// cannot disturb the envelope, the certificate chain or the payload.
fn real_attestation_with_tampered_signature() -> Vec<u8> {
	let mut bytes = real_attestation_bytes();
	*bytes.last_mut().expect("document is not empty") ^= 0x01;
	bytes
}

/// Flip one bit of a PCR value inside the real document's signed payload.
///
/// PCR bytes are covered by the signature but are read only after it is checked, so this reaches
/// `verify_cose_signature` rather than failing earlier on the certificate chain.
fn real_attestation_with_tampered_payload() -> Vec<u8> {
	let mut bytes = real_attestation_bytes();
	let (_, attestation) =
		crate::nsm::parse_cose_attestation_doc(&bytes).expect("real document parses");
	let pcr0 = attestation.pcrs.get(&0).expect("real document has PCR0");

	let offset = bytes
		.windows(pcr0.len())
		.position(|window| window == pcr0.as_slice())
		.expect("PCR0 appears verbatim in the encoded document");

	bytes[offset] ^= 0x01;
	bytes
}

/// A valid DER certificate that is not the Nitro root: the real document's own leaf.
///
/// Using it as the trust anchor exercises chain building against an untrusted root, rather than
/// failing earlier on a malformed anchor.
fn untrusted_root_certificate() -> Vec<u8> {
	let bytes = real_attestation_bytes();
	let (_, attestation) =
		crate::nsm::parse_cose_attestation_doc(&bytes).expect("real document parses");
	attestation.certificate.into_vec()
}

/// Generate a fake attestation with self-signed certificate
fn generate_fake_attestation_self_signed() -> Vec<u8> {
	let config = SimpleFakeAttestationConfig::default();
	generate_simple_fake_attestation_self_signed(&config).unwrap()
}

/// Generate a fake attestation with invalid certificate chain
fn generate_fake_attestation_invalid_cert_chain() -> Vec<u8> {
	let config = SimpleFakeAttestationConfig {
		certificate: vec![0x00; 4],
		..Default::default()
	};

	generate_simple_fake_attestation_self_signed(&config).unwrap()
}

// ============================================================================
// COMPREHENSIVE FAKE ATTESTATION TESTS
// ============================================================================

#[test]
fn test_attestation_doc_wrong_cert() {
	let attestation_doc_base64 = "hEShATgioFkRIr9pbW9kdWxlX2lkeCdpLTA1ZWJjMGQ5NjA3ZmM5NmE1LWVuYzAxOThmODFjNDU3N2UyMjFmZGlnZXN0ZlNIQTM4NGl0aW1lc3RhbXAbAAABmPgdzaRkcGNyc7AAWDBbYRHlpypb+2CuOUuqu+HwAABGzhP38vZ/1p4eISupD+U6+VoBue7p5yJ5XQZAa10BWDBLTVs2YbPvwSkgkAyA4Sbkzng8Ui3mwCoqW/evOiuTJ7hndvGI5L4cHEBKEp29pJMCWDC3xhXZz2PHZtsNc2jeicksYaSlkrqZ02riJM6XbJlCAA0G/K0/Yr5zmYmzJnccjHADWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEWDBC5kqqz2ZyIhfaU22++SPSr5YdIgRDpXUPEthGJsL3NZJ5R8Y5OKFCuFeEsMcfnBEFWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABrY2VydGlmaWNhdGVZAn8wggJ7MIICAaADAgECAhABmPgcRXfiIQAAAABosjRbMAoGCCqGSM49BAMDMIGOMQswCQYDVQQGEwJVUzETMBEGA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEPMA0GA1UECgwGQW1hem9uMQwwCgYDVQQLDANBV1MxOTA3BgNVBAMMMGktMDVlYmMwZDk2MDdmYzk2YTUudXMtZWFzdC0xLmF3cy5uaXRyby1lbmNsYXZlczAeFw0yNTA4MjkyMzE0MzJaFw0yNTA4MzAwMjE0MzVaMIGTMQswCQYDVQQGEwJVUzETMBEGA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEPMA0GA1UECgwGQW1hem9uMQwwCgYDVQQLDANBV1MxPjA8BgNVBAMMNWktMDVlYmMwZDk2MDdmYzk2YTUtZW5jMDE5OGY4MWM0NTc3ZTIyMS51cy1lYXN0LTEuYXdzMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEzsjQh2qdKjmMaueI61tEOZYS/GAOU4Tx3BG5PNntMRQt1f9Sn6Coy/MG/5VlD7G6rXifUSxUbTFP/aPqsUqb52wy0ZbSf+RD6aD6P6IQ0lj09bjdWfycce3Vnao4Q9S5ox0wGzAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwIGwDAKBggqhkjOPQQDAwNoADBlAjEAw6a5Xm01lWTJINTmUb5089FvZhhKf5fExh+BT/fduDJa/o8AdEDnH0bTMcoqHYAeAjBv/zITSQXfhRx90MljE3jeQNfAY8RM8hcHo+B4PZFGSLHJaESYcQsdN4hTFVUFoaJoY2FidW5kbGWEWQIVMIICETCCAZagAwIBAgIRAPkxdWgbkK/hHUbMtOTn+FYwCgYIKoZIzj0EAwMwSTELMAkGA1UEBhMCVVMxDzANBgNVBAoMBkFtYXpvbjEMMAoGA1UECwwDQVdTMRswGQYDVQQDDBJhd3Mubml0cm8tZW5jbGF2ZXMwHhcNMTkxMDI4MTMyODA1WhcNNDkxMDI4MTQyODA1WjBJMQswCQYDVQQGEwJVUzEPMA0GA1UECgwGQW1hem9uMQwwCgYDVQQLDANBV1MxGzAZBgNVBAMMEmF3cy5uaXRyby1lbmNsYXZlczB2MBAGByqGSM49AgEGBSuBBAAiA2IABPwCVOumCMHzaHDimtqQvkY4MpJzbolL//Zy2YlES1BR5TSksfbb48C8WBoyt7F2Bw7eEtaaP+ohG2bnUs990d0JX28TcPQXCEPZ3BABIeTPYwEoCWZEh8l5YoQwTcU/9KNCMEAwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUkCW1DdkFR+eWw5b6cp3PmanfS5YwDgYDVR0PAQH/BAQDAgGGMAoGCCqGSM49BAMDA2kAMGYCMQCjfy+Rocm9Xue4YnwWmNJVA44fA0P5W2OpYow9OYCVRaEevL8uO1XYru5xtMPWrfMCMQCi85sWBbJwKKXdS6BptQFuZbT73o/gBh1qUxl/nNr12UO8Yfwr6wPLb+6NIwLz3/ZZAsMwggK/MIICRKADAgECAhAmoyigtuiBDoA4D2rM1OsVMAoGCCqGSM49BAMDMEkxCzAJBgNVBAYTAlVTMQ8wDQYDVQQKDAZBbWF6b24xDDAKBgNVBAsMA0FXUzEbMBkGA1UEAwwSYXdzLm5pdHJvLWVuY2xhdmVzMB4XDTI1MDgyOTAyMzI1NVoXDTI1MDkxODAzMzI1NVowZDELMAkGA1UEBhMCVVMxDzANBgNVBAoMBkFtYXpvbjEMMAoGA1UECwwDQVdTMTYwNAYDVQQDDC0yZmY3YmZmYzFlMjQ0ZDFmLnVzLWVhc3QtMS5hd3Mubml0cm8tZW5jbGF2ZXMwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAATi5/XZm/U0Rswtdy+N1SqbFeb4xThraGKkFwxbVIT4OS1OR29U7a0sxY7xc2bne+6CpaI+IHI0bk37DPBVkwo9dNrc8GCB36O3vg64whWLcv1rtzbiJhvbqCiuDXAM+iujgdUwgdIwEgYDVR0TAQH/BAgwBgEB/wIBAjAfBgNVHSMEGDAWgBSQJbUN2QVH55bDlvpync+Zqd9LljAdBgNVHQ4EFgQUrMBC23uzRoAwuggnhrCk2C5VEuIwDgYDVR0PAQH/BAQDAgGGMGwGA1UdHwRlMGMwYaBfoF2GW2h0dHA6Ly9hd3Mtbml0cm8tZW5jbGF2ZXMtY3JsLnMzLmFtYXpvbmF3cy5jb20vY3JsL2FiNDk2MGNjLTdkNjMtNDJiZC05ZTlmLTU5MzM4Y2I2N2Y4NC5jcmwwCgYIKoZIzj0EAwMDaQAwZgIxALZpNLiMIXrVnCBduL6rctghkUpqABUKFN6/nyiD5SSJqDRxMSUp8TRRx4lZ8t8cxwIxAK/5c/6BiEChCFyg0QuzK5kmvqZwSV6ZpHqq8hbVYcNTdaOYWwMCaK+kQXSvAAlEhlkDGTCCAxUwggKboAMCAQICEQDjJQdsZuoKDOB1nhP9Z57rMAoGCCqGSM49BAMDMGQxCzAJBgNVBAYTAlVTMQ8wDQYDVQQKDAZBbWF6b24xDDAKBgNVBAsMA0FXUzE2MDQGA1UEAwwtMmZmN2JmZmMxZTI0NGQxZi51cy1lYXN0LTEuYXdzLm5pdHJvLWVuY2xhdmVzMB4XDTI1MDgyOTE3MTMwMFoXDTI1MDkwNDE0MTMwMFowgYkxPDA6BgNVBAMMM2Y4YTRkNmU4MmUxM2JkNGYuem9uYWwudXMtZWFzdC0xLmF3cy5uaXRyby1lbmNsYXZlczEMMAoGA1UECwwDQVdTMQ8wDQYDVQQKDAZBbWF6b24xCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJXQTEQMA4GA1UEBwwHU2VhdHRsZTB2MBAGByqGSM49AgEGBSuBBAAiA2IABCiO8YCoFmvgHUkiu5aOFmxWVETMyghNWt+QH7PkKDPfYCpqrTm/NwD3OlreQQBfE1Bke7i+ptgQjPR5xrAqSOVlDzrnvVZiXKZOR/zw8/d5yijXDyUi9WOr2wiOL6yOgqOB6jCB5zASBgNVHRMBAf8ECDAGAQH/AgEBMB8GA1UdIwQYMBaAFKzAQtt7s0aAMLoIJ4awpNguVRLiMB0GA1UdDgQWBBQmPhxJXp/2mU6Ne9zZJj/pCUuSzTAOBgNVHQ8BAf8EBAMCAYYwgYAGA1UdHwR5MHcwdaBzoHGGb2h0dHA6Ly9jcmwtdXMtZWFzdC0xLWF3cy1uaXRyby1lbmNsYXZlcy5zMy51cy1lYXN0LTEuYW1hem9uYXdzLmNvbS9jcmwvZDYyYzU5MWEtNDI4ZS00YTg1LWIzNGQtMjNmZWNkZDhiMmNkLmNybDAKBggqhkjOPQQDAwNoADBlAjBOkaQpec5TDLLTzFLZDjoi58Vf5rVQZ1BzzEdhMgGeD8QM+wWqjmIo/H6BcT/kjMcCMQD5kvtk2tr50NlbHbKlV9FN7p8PISzM8WIiW8y3ZOFHpeja28aS/sjuycqvHxfwEK9ZAsIwggK+MIICRKADAgECAhR8eyAQHBl5Lap7xBqcwz90E4b2ZjAKBggqhkjOPQQDAzCBiTE8MDoGA1UEAwwzZjhhNGQ2ZTgyZTEzYmQ0Zi56b25hbC51cy1lYXN0LTEuYXdzLm5pdHJvLWVuY2xhdmVzMQwwCgYDVQQLDANBV1MxDzANBgNVBAoMBkFtYXpvbjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAldBMRAwDgYDVQQHDAdTZWF0dGxlMB4XDTI1MDgyOTIzMDMyOFoXDTI1MDgzMDIzMDMyOFowgY4xCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMQ8wDQYDVQQKDAZBbWF6b24xDDAKBgNVBAsMA0FXUzE5MDcGA1UEAwwwaS0wNWViYzBkOTYwN2ZjOTZhNS51cy1lYXN0LTEuYXdzLm5pdHJvLWVuY2xhdmVzMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEdZB1sAmFYw200Y81VTQXjfl9BuH8Uoal/GMNvVcOm/KkVBN9AOAOzEXLDDRhkESAoYlutCLrj56o/MD2qAub4TrDjNv4+vIFjZkXoIvZ12okwq1wm2C6d+4AqxCPiuRyo2YwZDASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwICBDAdBgNVHQ4EFgQUhCrJGy6fFZp1I4DhWqm98RzLMAQwHwYDVR0jBBgwFoAUJj4cSV6f9plOjXvc2SY/6QlLks0wCgYIKoZIzj0EAwMDaAAwZQIwRfXqjpj3QIe25wVmzL5oB0wOYZwPuwZqYwyNjD/OpwQ8lUVH+apsLw9BD101HU9OAjEAumReQRIFafmv3Ig3k+K7LbFRT/dYMK1MoYyyUwJrJg3XwS3gU/4KAFtEFSO6xqKeanB1YmxpY19rZXlYIAXI1LL6uC850yD/D3qBX1HtYaK342A46z5MslerZbhoaXVzZXJfZGF0YfZlbm9uY2X2/1hgbeGerhQvaLtC6M4FxZkxJFHiC7SWr3LIUtavo5gjC854UVaAdX4J74+9bFfMal7kil9o5aOfC+yoKJYVdwaw6Z0y1fpas87aG35t1EoAiSsCr/g8uT8dj3WqJjOGcC/w";

	let attestation_doc_bytes = STANDARD
		.decode(attestation_doc_base64)
		.expect("Failed to decode base64");

	// Create a custom verifier with extended max age to handle expired attestations for testing
	let pcr_configs = vec![]; // We'll add them below
	let bad_cert = b"-----BEGIN CERTIFICATE-----
    AIICETCCAZagAwIBAgIRAPkxdWgbkK/hHUbMtOTn+FYwCgYIKoZIzj0EAwMwSTEL
    MAkGA1UEBhMCVVMxDzANBgNVBAoMBkFtYXpvbjEMMAoGA1UECwwDQVdTMRswGQYD
    VQQDDBJhd3Mubml0cm8tZW5jbGF2ZXMwHhcNMTkxMDI4MTMyODA1WhcNNDkxMDI4
    MTQyODA1WjBJMQswCQYDVQQGEwJVUzEPMA0GA1UECgwGQW1hem9uMQwwCgYDVQQL
    DANBV1MxGzAZBgNVBAMMEmF3cy5uaXRyby1lbmNsYXZlczB2MBAGByqGSM49AgEG
    BSuBBAAiA2IABPwCVOumCMHzaHDimtqQvkY4MpJzbolL//Zy2YlES1BR5TSksfbb
    48C8WBoyt7F2Bw7eEtaaP+ohG2bnUs990d0JX28TcPQXCEPZ3BABIeTPYwEoCWZE
    h8l5YoQwTcU/9KNCMEAwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUkCW1DdkF
    R+eWw5b6cp3PmanfS5YwDgYDVR0PAQH/BAQDAgGGMAoGCCqGSM49BAMDA2kAMGYC
    MQCjfy+Rocm9Xue4YnwWmNJVA44fA0P5W2OpYow9OYCVRaEevL8uO1XYru5xtMPW
    rfMCMQCi85sWBbJwKKXdS6BptQFuZbT73o/gBh1qUxl/nNr12UO8Yfwr6wPLb+6N
    IwLz3/Y=
    -----END CERTIFICATE-----"
		.to_vec();

	let ten_years_in_milliseconds = 10 * 365 * 24 * 60 * 60 * 1000; // 10 years in milliseconds (for testing)

	let mut verifier = EnclaveAttestationVerifier::new_with_config_and_time_skip(
		pcr_configs,
		bad_cert,
		ten_years_in_milliseconds,
		true, // Skip certificate time checks for testing
	);

	// These are real PCR values generated by an enclave in time
	verifier.add_allowed_pcr_config(vec![
		PcrMeasurement::new(
			0,
			hex_literal::hex!(
				"5b6111e5a72a5bfb60ae394baabbe1f0000046ce13f7f2f67fd69e1e212ba90fe53af95a01b9eee9e722795d06406b5d"
			),
		),
		PcrMeasurement::new(
			1,
			hex_literal::hex!(
				"4b4d5b3661b3efc12920900c80e126e4ce783c522de6c02a2a5bf7af3a2b9327b86776f188e4be1c1c404a129dbda493"
			),
		),
		PcrMeasurement::new(
			2,
			hex_literal::hex!(
				"b7c615d9cf63c766db0d7368de89c92c61a4a592ba99d36ae224ce976c9942000d06fcad3f62be739989b326771c8c70"
			),
		),
	]);

	// Verify the attestation document
	let result = verifier.verify_document(&attestation_doc_bytes);

	assert!(result.is_err(), "Should have failed with bad certificate");
}

#[test]
fn test_attestation_with_different_root_ca() {
	// The document is genuine; only the trust anchor is wrong.
	let attestation = real_attestation_bytes();

	let verifier = EnclaveAttestationVerifier::new_with_config_and_time_skip(
		vec![],
		untrusted_root_certificate(),
		60000,
		true,
	);

	let result = verifier.verify_document(&attestation);
	assert!(
		matches!(
			result,
			Err(EnclaveAttestationError::AttestationChainInvalid(_))
		),
		"Should reject attestation that does not chain to the configured root, got {result:?}"
	);
}

#[test]
fn test_attestation_with_self_signed_certificate() {
	let fake_attestation = generate_fake_attestation_self_signed();

	let verifier = EnclaveAttestationVerifier::new_with_config_and_time_skip(
		vec![],
		constants::AWS_NITRO_ROOT_CERT.to_vec(),
		60000,
		true,
	);

	let result = verifier.verify_document(&fake_attestation);
	assert!(
		matches!(
			result,
			Err(EnclaveAttestationError::AttestationChainInvalid(_))
		),
		"Should reject self-signed certificate, got {result:?}"
	);
}

/// A tampered signature must be rejected by `verify_cose_signature`.
///
/// Every other negative fixture fails at the certificate chain, so without this test the suite
/// still passes with the signature check removed entirely.
#[test]
fn test_attestation_with_tampered_signature() {
	let (verifier, _) = get_real_attestation_document();

	let result = verifier.verify_document(&real_attestation_with_tampered_signature());
	assert!(
		matches!(
			result,
			Err(EnclaveAttestationError::AttestationSignatureInvalid(_))
		),
		"Should reject a tampered signature, got {result:?}"
	);
}

/// A tampered payload must be rejected too: the payload is part of the COSE `Sig_structure`.
#[test]
fn test_attestation_with_tampered_payload() {
	let (verifier, _) = get_real_attestation_document();

	let result = verifier.verify_document(&real_attestation_with_tampered_payload());
	assert!(
		matches!(
			result,
			Err(EnclaveAttestationError::AttestationSignatureInvalid(_))
		),
		"Should reject a tampered payload, got {result:?}"
	);
}

/// Trailing bytes after the COSE envelope are outside the signature, so they must be rejected.
#[test]
fn test_attestation_with_trailing_bytes() {
	let (verifier, _) = get_real_attestation_document();

	let mut attestation = real_attestation_bytes();
	attestation.extend_from_slice(&[0xf6, 0xf6, 0xf6]);

	let result = verifier.verify_document(&attestation);
	assert!(
		matches!(
			result,
			Err(EnclaveAttestationError::AttestationDocumentParseError(_))
		),
		"Should reject unsigned trailing data, got {result:?}"
	);
}

#[test]
fn test_attestation_with_invalid_certificate_chain() {
	let fake_attestation = generate_fake_attestation_invalid_cert_chain();

	let verifier = EnclaveAttestationVerifier::new_with_config_and_time_skip(
		vec![],
		constants::AWS_NITRO_ROOT_CERT.to_vec(),
		60000,
		true,
	);

	let result = verifier.verify_document(&fake_attestation);
	assert!(
		matches!(
			result,
			Err(EnclaveAttestationError::AttestationChainInvalid(_))
		),
		"Should reject invalid certificate chain, got {result:?}"
	);
}

#[test]
fn test_attestation_with_expired_certificate() {
	// The real document's certificates expired in 2025; every other test opts out of the check.
	let (mut verifier, _) = get_real_attestation_document();
	verifier.skip_certificate_time_check = false;

	let result = verifier.verify_document(&real_attestation_bytes());
	assert!(
		matches!(
			result,
			Err(EnclaveAttestationError::AttestationChainInvalid(_))
		),
		"Should reject expired certificate, got {result:?}"
	);
}

#[test]
fn test_attestation_that_is_stale() {
	let (mut verifier, _) = get_real_attestation_document();
	verifier.max_age_millis = 60_000;

	let result = verifier.verify_document(&real_attestation_bytes());
	assert!(
		matches!(
			result,
			Err(EnclaveAttestationError::AttestationStale { .. })
		),
		"Should reject a stale attestation, got {result:?}"
	);
}

#[test]
fn test_attestation_with_mismatched_pcrs() {
	// PCR validation runs after the chain and signature checks, so this needs the real document.
	let (mut verifier, _) = get_real_attestation_document();
	verifier.allowed_pcr_configs.clear();
	verifier.add_allowed_pcr_config(vec![
		PcrMeasurement::new(0, [0xAA; 48]),
		PcrMeasurement::new(1, [0xBB; 48]),
	]);

	let result = verifier.verify_document(&real_attestation_bytes());
	assert!(
		matches!(result, Err(EnclaveAttestationError::CodeUntrusted { .. })),
		"Should reject mismatched PCR values, got {result:?}"
	);
}

#[test]
fn test_multiple_pcr_configurations_success() {
	// This test verifies that PCR validation succeeds when ANY configuration matches,
	// not requiring ALL configurations to match. This enables support for multiple
	// enclave versions with different PCR values.

	let (mut verifier, attestation_doc_base64) = get_real_attestation_document();

	// Clear existing configurations
	verifier.allowed_pcr_configs.clear();

	// Add the correct PCR configuration (from the real attestation)
	let correct_config = vec![
		PcrMeasurement::new(
			0,
			hex_literal::hex!(
				"108b32466f5dc0a9971e0bc8e3e4074e7821bb2dcad3841bdec9a08b30f173386f0394a01486df181f316b39443dab34"
			),
		),
		PcrMeasurement::new(
			1,
			hex_literal::hex!(
				"4b4d5b3661b3efc12920900c80e126e4ce783c522de6c02a2a5bf7af3a2b9327b86776f188e4be1c1c404a129dbda493"
			),
		),
		PcrMeasurement::new(
			2,
			hex_literal::hex!(
				"08c6b2cba2d0c0ab63f3533cb44e092fb211775323cd62cd571f871e127ae1844f0e948a54ba58ecd29fbe03a64d5edc"
			),
		),
		PcrMeasurement::new(
			8,
			hex_literal::hex!(
				"b38251662033340b540c2d7e5f49e7ec6d10afcb5f17c72132e20a7f0a54576dc4d2c6ce062ed2ed2b6ae01815d69c8d"
			),
		),
	];

	// Add a completely different configuration (simulating a different enclave version)
	// Each PCR value must be exactly 48 bytes (96 hex characters) for SHA-384
	let different_config = vec![
		PcrMeasurement::new(0, [0xff; 48]),
		PcrMeasurement::new(1, [0xee; 48]),
		PcrMeasurement::new(2, [0xdd; 48]),
		PcrMeasurement::new(8, [0xcc; 48]),
	];

	// Add both configurations - the attestation should succeed because ONE matches
	verifier.allowed_pcr_configs.push(different_config.clone());
	verifier.allowed_pcr_configs.push(correct_config);

	let attestation_doc_bytes = STANDARD
		.decode(attestation_doc_base64)
		.expect("Failed to decode base64");

	// This should SUCCEED because one configuration matches
	verifier
		.verify_document(&attestation_doc_bytes)
		.expect("one PCR configuration matches, so verification must succeed");

	// Now test with ONLY non-matching configurations - should fail
	verifier.allowed_pcr_configs.clear();
	verifier.allowed_pcr_configs.push(different_config);

	let another_different_config = vec![
		PcrMeasurement::new(0, [0xaa; 48]),
		PcrMeasurement::new(1, [0xbb; 48]),
		PcrMeasurement::new(2, [0x11; 48]),
		PcrMeasurement::new(8, [0x22; 48]),
	];
	verifier.allowed_pcr_configs.push(another_different_config);

	let result = verifier.verify_document(&attestation_doc_bytes);

	// This should FAIL because no configuration matches
	assert!(
		matches!(result, Err(EnclaveAttestationError::CodeUntrusted { .. })),
		"Should reject attestation when no PCR configuration matches, got {result:?}"
	);
}
